# .github/workflows/ht-pdf.yaml
name: ht-pdf Action
on: 
  [push]
  repository_dispatch:
    types: 
      - htpdf

jobs:
  ht-pdf:
    runs-on: ubuntu-latest
    name: HT pdf processing
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Clone ht-pdf private repository
        uses: actions/checkout@v3
        with:
          repository: 'plindman/ht-pdf'
          token: ${{ secrets.HTPDFREPO }}
          path: ''
      - name: View merged files structure after repository content clone 
        run: |
          ls -la ${{ github.workspace }}/src
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  
      - name: Install Dependencies
        run: pip install -r requirements.txt
        shell: bash
      - name: Run the generate_pdf script
        id: generate-pdf-flow
        uses: ./generate-pdf-action/
