# .github/workflows/test_action.yaml
name: Python Demo Action
on: [push]

jobs:
  get-num-square:
    runs-on: ubuntu-latest
    name: Returns the number square
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          find ${{ github.workspace }} -type f
      - name: Fetch num squared
        id: get_square
        uses: /actions/python-demo-action.yml
        # Uses the action we created in local repo
        # or use a released GitHub Action
        # uses: shipyard/github-action/fetch-shipyard-env@1.0.0
        with:
          num: 11
      - name: Print the square
        run: echo "${{ steps.get_square.outputs.num_squared }}"